language: ruby
rvm:
 - 1.8.7
 - 1.9.2
 - 1.9.3
 - ruby-head
 - jruby
 - rbx
 - ree

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq -y graphicsmagick imagemagick

matrix:
  allow_failures:
    - rvm: ruby-head
